blank_issues_enabled: false
contact_links:
  - name: Mod Page
    url: https://mods.vintagestory.at/wist
    about: Please direct any questions or general feedback to the modDB page or modding discord.
